src/Entity/Component.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ComponentRepository")
 */
class Component implements \JsonSerializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="types")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $format;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=140, nullable=true)
     */
    private $text;

    /**
     * @ORM\Column(type="integer")
     */
    private $x_axis;

    /**
     * @ORM\Column(type="integer")
     */
    private $y_axis;

    /**
     * @ORM\Column(type="integer")
     */
    private $z_axis;

    /**
     * @ORM\Column(type="integer")
     */
    private $width;

    /**
     * @ORM\Column(type="integer")
     */
    private $height;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="components")
     */
    private $ad;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function setFormat(string $format): self
    {
        $this->format = $format;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getXAxis(): ?int
    {
        return $this->x_axis;
    }

    public function setXAxis(int $x_axis): self
    {
        $this->x_axis = $x_axis;

        return $this;
    }

    public function getYAxis(): ?int
    {
        return $this->y_axis;
    }

    public function setYAxis(int $y_axis): self
    {
        $this->y_axis = $y_axis;

        return $this;
    }

    public function getZAxis(): ?int
    {
        return $this->z_axis;
    }

    public function setZAxis(int $z_axis): self
    {
        $this->z_axis = $z_axis;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(int $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function jsonSerialize() : array
    {
        return [
            'id' => $this->id,
            'ad' => $this->ad,
            'name' => $this->name,
            'type' => $this->type,
            'link' => $this->link,
            'format' => $this->format,
            'size' => $this->size,
            'text' => $this->text,
            'x_axis' => $this->x_axis,
            'y_axis' => $this->y_axis,
            'z_axis' => $this->z_axis,
            'width' => $this->width,
            'height' => $this->height,
            'created_at' => $this->created_at,
        ];
    }
}

src/Form/ComponentType.php
<?php

namespace App\Form;

use App\Entity\Component;
use App\Entity\Type;
use App\Entity\Ad;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ComponentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class,[
                'label' => 'Nombre'
            ])
            ->add('type', EntityType::class,[
                'class' => Type::class,
                'label' => 'Tipo'
            ])
            ->add('link', TextType::class)
            ->add('format', ChoiceType::class)
            ->add('size', NumberType::class)
            ->add('text', TextType::class,[
                'attr' => ['class' => 'cont-chars'],
            ])
            
            ->add('x_axis', NumberType::class)
            ->add('y_axis', NumberType::class)
            ->add('z_axis', NumberType::class)
            ->add('width', NumberType::class)
            ->add('height', NumberType::class)
            ->add('ad', EntityType::class,[
                'class' => Ad::class,
                'label' => 'Ad'
            ])
            ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $component = $event->getData();
            $form = $event->getForm();
            if ($component->getType() == 'Imagen'){
                $form->add('format', ChoiceType::class,[
                    'choices' => ['PNG' => 'PNG', 'JPG' => 'JPG']
                ]);
            } elseif ($component->getType() == 'Video') {
                $form->add('format', ChoiceType::class,[
                    'choices' => ['MP4' => 'MP4', 'WEBM' => 'WEBM']
                ]);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Component::class,
        ]);
    }
}

src/Controller/ComponentController.php
<?php

namespace App\Controller;

use App\Entity\Component;
use App\Form\ComponentType;
use App\Repository\ComponentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/component")
 */
class ComponentController extends AbstractController
{
    /**
     * @Route("/", name="component_index", methods={"GET"})
     */
    public function index(ComponentRepository $componentRepository): Response
    {
        return $this->render('component/index.html.twig', [
            'components' => $componentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="component_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $component = new Component();
        $form = $this->createForm(ComponentType::class, $component);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $component->setCreatedAt(new \DateTime());
            $entityManager->persist($component);
            $entityManager->flush();

            return $this->redirectToRoute('component_index');
        }

        return $this->render('component/new.html.twig', [
            'component' => $component,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="component_show", methods={"GET"})
     */
    public function show(Component $component): Response
    {
        return $this->render('component/show.html.twig', [
            'component' => $component,
        ]);
    }

    /**
     * @Route("/{id}/front", name="component_front", methods={"GET","POST"})
     */
    public function frontjson(Component $component): JsonResponse
    {
        return new JsonResponse(
            $component,
            JsonResponse::HTTP_OK
        );
    }

    /**
     * @Route("/{id}/edit", name="component_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Component $component): Response
    {
        $form = $this->createForm(ComponentType::class, $component);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('component_index', [
                'id' => $component->getId(),
            ]);
        }

        return $this->render('component/edit.html.twig', [
            'component' => $component,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="component_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Component $component): Response
    {
        if ($this->isCsrfTokenValid('delete'.$component->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($component);
            $entityManager->flush();
        }

        return $this->redirectToRoute('component_index');
    }
}

templates/component/_delete_form.html.twig
<form method="post" action="{{ path('component_delete', {'id': component.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ component.id) }}">
    <button class="btn">Delete</button>
</form>

templates/component/_form.html.twig
{{ form_start(form) }}
    {# {{ form_widget(form) }} #}
    {{ form_row(form.ad) }}
    {{ form_row(form.name) }}
    {{ form_row(form.type) }}
    {{ form_row(form.text, {'required': false, 'attr': {'class': 'choice_type cont-char'}}) }}
    {{ form_row(form.link, {'required': false, 'attr': {'class': 'choice_type'}}) }}
    {{ form_row(form.size, {'required': false, 'attr': {'class': 'choice_type'}}) }}
    {{ form_row(form.format, {'required': false, 'attr': {'class': 'choice_type'}}) }}
    {{ form_row(form.x_axis) }}
    {{ form_row(form.y_axis) }}
    {{ form_row(form.z_axis) }}
    {{ form_row(form.width) }}
    {{ form_row(form.height) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/component/_modal_form.html.twig
    <div class="row">
        <div class="col-sm-12">
            <div class="btn btn-success">Add to ad</div>
            <select class="form-control d-inline-block" id="form_components">
                {% for component in components %}
                        <option value></option>
                        <option value="{{component.id}}">{{ component.name }} - {{ component.type.name }}</options>
                {% else %}
                    <option value>no records found</options>
                {% endfor %}
            </select>
        </div>
    </div>


    {# {% for component in ad_components %}
            <tr>
                <td>{{ component.id }}</td>
                <td>{{ component.name }}</td>
                <td>{{ component.type.name }}</td>
                <td>{{ component.link }}</td>
                <td>{{ component.format }}</td>
                <td>{{ component.size }}</td>
                <td>{{ component.text }}</td>
                <td>{{ component.xAxis }}</td>
                <td>{{ component.yAxis }}</td>
                <td>{{ component.zAxis }}</td>
                <td>{{ component.width }}</td>
                <td>{{ component.height }}</td>
                <td><small>{{ component.createdAt ? component.createdAt|date('Y-m-d H:i:s') : '' }}</small></td>
                <td>
                    <a href="{{ path('component_show', {'id': component.id}) }}" class="btn btn-primary btn-sm">pick</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %} #}


<!-- The Modal -->
<div class="modal" id="addComponent">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Select Component</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">

        {{ form_start(form_component) }}
            {# {{ form_widget(form_component) }} #}
            {{ form_row(form_component.name) }}
            {{ form_row(form_component.type) }}
            {{ form_row(form_component.text, {'required': false, 'attr': {'class': 'choice_type'}}) }}
            {{ form_row(form_component.link, {'required': false, 'attr': {'class': 'choice_type'}}) }}
            {{ form_row(form_component.size, {'required': false, 'attr': {'class': 'choice_type'}}) }}
            {{ form_row(form_component.format, {'required': false, 'attr': {'class': 'choice_type'}}) }}
            {{ form_row(form_component.x_axis) }}
            {{ form_row(form_component.y_axis) }}
            {{ form_row(form_component.z_axis) }}
            {{ form_row(form_component.width) }}
            {{ form_row(form_component.height) }}
            <button class="btn btn-success">{{ button_label|default('Save') }}</button>
        {{ form_end(form_component) }}

        
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

templates/component/_table.html.twig
<h1>Component index</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Ad Name</th>
            <th>Name</th>
            <th>Type</th>
            <th>Link</th>
            <th>Format</th>
            <th>Size</th>
            <th>Text</th>
            <th>X/Y/Z Axis</th>
            <th>Width/Height</th>
            <th>Created_at</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
    {% for component in components %}
        <tr>
            <td>{{ component.id }}</td>
            <td>{{ component.ad}}</td>
            <td>{{ component.name }}</td>
            <td>{{ component.type.name }}</td>
            <td>{% if (component.link != '')  %}<a href="{{ component.link }}" target="_blank">link</a>{% endif %}</td>
            <td>{{ component.format }}</td>
            <td>{{ component.size }}</td>
            <td>{{ component.text }}</td>
            <td>{{ component.xAxis }}/{{ component.yAxis }}/{{ component.zAxis }}</td>
            <td>{{ component.width }}/{{ component.height }}</td>
            <td align="center"><small>{{ component.createdAt ? component.createdAt|date('Y-m-d H:i:s') : '' }}</small></td>
            <td>
                {# <a href="{{ path('component_show', {'id': component.id}) }}" class="btn btn-primary btn-sm">show</a> #}
                <a href="{{ path('component_edit', {'id': component.id}) }}" class="btn btn-primary btn-sm my-1">edit</a>
                <a href="{{ path('component_front', {'id': component.id}) }}" target="_blank" class="btn btn-primary btn-sm my-1">JSON</a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="13">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<a href="{{ path('component_new') }}">Create new</a>

templates/component/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Component{% endblock %}

{% block body %}
    <h1>Edit Component</h1>

    {{ include('component/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('component_index') }}">back to list</a>

    {{ include('component/_delete_form.html.twig') }}
{% endblock %}

{% block javascripts %}
    <script>
    $(document).ready(function(){
       app.init();
    })
    </script>
{% endblock %}

templates/component/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Component index{% endblock %}

{% block body %}
    {{ include('component/_table.html.twig') }}
{% endblock %}

templates/component/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Component{% endblock %}

{% block body %}
    <h1>Create new Component</h1>

    {{ include('component/_form.html.twig') }}

    <a href="{{ path('component_index') }}">back to list</a>
{% endblock %}

{% block javascripts %}
    <script>
    $(document).ready(function(){
       app.init();
    })
    </script>
{% endblock %}

templates/component/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Component{% endblock %}

{% block body %}
    <h1>Component</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ component.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ component.name }}</td>
            </tr>
            <tr>
                <th>Link</th>
                <td>{{ component.link }}</td>
            </tr>
            <tr>
                <th>Format</th>
                <td>{{ component.format }}</td>
            </tr>
            <tr>
                <th>Size</th>
                <td>{{ component.size }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ component.text }}</td>
            </tr>
            <tr>
                <th>X_axis</th>
                <td>{{ component.xAxis }}</td>
            </tr>
            <tr>
                <th>Y_axis</th>
                <td>{{ component.yAxis }}</td>
            </tr>
            <tr>
                <th>Z_axis</th>
                <td>{{ component.zAxis }}</td>
            </tr>
            <tr>
                <th>Width</th>
                <td>{{ component.width }}</td>
            </tr>
            <tr>
                <th>Height</th>
                <td>{{ component.height }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ component.createdAt ? component.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('component_index') }}">back to list</a>

    <a href="{{ path('component_edit', {'id': component.id}) }}">edit</a>

    {{ include('component/_delete_form.html.twig') }}
{% endblock %}